### ISSUE TITLE
Emulation examples have been broken with recent changes in INET 4.1

### ISSUE THREAD

**Issue by levy** [inet-framework/inet-showcases#35]
See examples/emulation/extserver for example.

**Comment by lbarbierato** [comment]
Dear Levy,

I would like to report my simulation attempt to make a TCP tunneling through Omnet++ with INET4.1 ExtUpperEthernetInterface:

1. Generate two namespace for TCP server and client 
```
# create network namespaces
sudo ip netns add host0
sudo ip netns add host1

# create TAP interfaces
sudo ip netns exec host0 ip tuntap add mode tap dev tap0
sudo ip netns exec host1 ip tuntap add mode tap dev tap1

# bring up TAP interfaces
sudo ip netns exec host0 ip link set dev tap0 up
sudo ip netns exec host1 ip link set dev tap1 up

# assign IP addresses to interface
sudo ip netns exec host0 ip addr add 10.0.0.1/32 dev tap0
sudo ip netns exec host1 ip addr add 10.0.1.1/32 dev tap1

# add routing table
sudo ip netns exec host0 route add default gw 10.0.0.1 dev tap0
sudo ip netns exec host1 route add default gw 10.0.1.1 dev tap1
```

2. Start the TCP server

```
sudo ip netns exec host1 python3 server.py
```

3. Omnetpp.ini

```
[General]
scheduler-class = "inet::RealTimeScheduler"
sim-time-limit = 3600s
cmdenv-express-mode = false

**.crcMode = "computed"
**.fcsMode = "computed"

[Config ExternalCommunication]
network = ExternalCommunication
description = "UDP tunneling through Omnet++"

**.router.ipv4.routingTable.routingFile = "router.mrt"
**.host1.ipv4.routingTable.routingFile = "host1.mrt"
**.host2.ipv4.routingTable.routingFile = "host2.mrt"

*.host1.eth[0].typename = "ExtUpperEthernetInterface"
*.host1.eth[0].device = "tap0"
*.host1.eth[0].copyConfiguration = "copyFromExt"
*.host1.eth[0].namespace = "host0"

*.host2.eth[0].typename = "ExtUpperEthernetInterface"
*.host2.eth[0].device = "tap1"
*.host2.eth[0].copyConfiguration = "copyFromExt"
*.host2.eth[0].namespace = "host1"
```

4. NED file

```
package inet.showcases.emulation.basic;

import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.inet.Router;
import inet.node.ethernet.Eth100M;
import inet.node.inet.AdhocHost;
import inet.node.inet.StandardHost;
import inet.physicallayer.contract.packetlevel.IRadioMedium;
import inet.physicallayer.ieee80211.packetlevel.Ieee80211ScalarRadioMedium;
import ned.DatarateChannel;


network ExternalCommunication
{
    parameters:
        @display("bgb=600,300");
    submodules:
        configurator: Ipv4NetworkConfigurator {
            parameters:
                @display("p=100,100;is=s");
        }
        host1: StandardHost {
            parameters:
                @display("p=300,150");
            gates:
                pppg[1];
        }
        host2: StandardHost {
            parameters:
                @display("p=500,150");
            gates:
                pppg[1];
        }
        router: Router {
            parameters:
                @display("p=400,150");
            gates:
                pppg[2];
        	
        }
    connections allowunconnected:
        router.pppg[0]  <--> NormalPath <--> host1.pppg[0];
        router.pppg[1]  <--> NormalPath <--> host2.pppg[0];
}

channel NormalPath extends DatarateChannel
{
    parameters:
        datarate = 100Mbps;
        delay = 0.0565us; // 10m
        per = 0;
        ber = 0;
}
```

5. Run the simulation

6. Run the TCP client

```
sudo ip netns exec host0 python3 client.py
```

This configuration discussed previously doesn't work. TCP client goes in Timeout Error.

Kind regards,
Luca

Attachment are routing table router.mrt, host1.mrt and host2.mrt
[routingTable.zip](https://github.com/inet-framework/inet-showcases/files/2961036/routingTable.zip)

**Comment by levy** [comment]
You are configuring ETH interfaces in your ini file, but you are connecting PPP interfaces in your NED file. Also, the default gateway and the mrt files are wrong. This example should work without problems if configured properly.

**Comment by lbarbierato** [comment]
Thanks Levente,

I just modify the NED file and used an Eth100M link between host0 <--> router <-->host1:

```
package inet.showcases.emulation.basic;

import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.inet.Router;
import inet.node.ethernet.Eth100M;
import inet.node.inet.AdhocHost;
import inet.node.inet.StandardHost;
import inet.physicallayer.contract.packetlevel.IRadioMedium;
import inet.physicallayer.ieee80211.packetlevel.Ieee80211ScalarRadioMedium;

network ExternalCommunication
{
    parameters:
        @display("bgb=600,300");
    submodules:
        configurator: Ipv4NetworkConfigurator {
            parameters:
                @display("p=100,100;is=s");
        }
        host0: StandardHost {
            parameters:
                @display("p=300,150");
        }
        host1: StandardHost {
            parameters:
                @display("p=500,150");
        }
        router: Router {
            parameters:
                @display("p=400,150");
        }
    connections allowunconnected:
        host0.ethg++ <--> Eth100M <--> router.ethg++;
        host1.ethg++ <--> Eth100M <--> router.ethg++;
}
```

and the omnetpp.ini eliminating the routing table to let the Ipv4NetworkConfigurator auto configuring the routing between nodes:

```
[General]
scheduler-class = "inet::RealTimeScheduler"
sim-time-limit = 3600s
cmdenv-express-mode = false

**.crcMode = "computed"
**.fcsMode = "computed"

[Config ExternalCommunication]
network = ExternalCommunication
description = "UDP tunneling through Omnet++"

*.host0.eth[0].typename = "ExtUpperEthernetInterface"
*.host0.eth[0].namespace = "host0"
*.host0.eth[0].device = "tap0"
*.host0.eth[0].copyConfiguration = "copyFromExt"


*.host1.eth[0].typename = "ExtUpperEthernetInterface"
*.host1.eth[0].namespace = "host1"
*.host1.eth[0].device = "tap1"
*.host1.eth[0].copyConfiguration = "copyFromExt"
```
now messages from the TCP client goes through the link between host0 and router. linklayer is correctly taking the MAC address and IP address of interface tap0/host0:

![host0](https://user-images.githubusercontent.com/12516481/54281720-a2caf180-459a-11e9-9d82-96dd71724047.png)

But then I noticed that router and host1 are not configured correctly:

![host1](https://user-images.githubusercontent.com/12516481/54281721-a3638800-459a-11e9-9822-40ddda2ddcef.png)

![router](https://user-images.githubusercontent.com/12516481/54281722-a3638800-459a-11e9-8b19-04823b2bf4df.png)

The issue is surely generated from Ipv4NetworkConfigurator. You tell me in the past messages on the Omnetpp Google group to avoid the usage of routing table such as in the previous example. But I don't find an example on how to configure properly the routing table. Can you help me in find the documentation to correctly configure the router?

Luca

**Comment by levy** [comment]
See https://inet.omnetpp.org/docs/tutorials/configurator/doc/index.html
I'm going to remove this bug, because this was accidentally added to the showcases repository instead of the main INET repository. Also, please take this conversation to the mailing list, because this bug is not related to it at all.

**Comment by lbarbierato** [comment]
SOLVED

```
[General]
scheduler-class = "inet::RealTimeScheduler"
sim-time-limit = 3600s
cmdenv-express-mode = false

**.crcMode = "computed"
**.fcsMode = "computed"

[Config ExternalCommunication]
network = ExternalCommunication
description = "UDP tunneling through Omnet++"

# Using inline XML configuration
*.configurator.config = xml("<config> \
                                <interface hosts='host0' names='eth0' address='10.0.0.1'/> \
                                <interface hosts='host1' names='eth0' address='10.0.1.1'/> \
				<interface hosts='router' names='eth0' address='10.0.0.100'/> \
                                <interface hosts='router' names='eth1' address='10.0.1.100'/> \
                             </config>")

*.host0.eth[0].typename = "ExtUpperEthernetInterface"
*.host0.eth[0].namespace = "host0"
*.host0.eth[0].device = "tap0"
*.host0.eth[0].copyConfiguration = "copyFromExt"


*.host1.eth[0].typename = "ExtUpperEthernetInterface"
*.host1.eth[0].namespace = "host1"
*.host1.eth[0].device = "tap1"
*.host1.eth[0].copyConfiguration = "copyFromExt"
```

**Comment by zhangteng0526** [comment]
> SOLVED
> 
> ```
> [General]
> scheduler-class = "inet::RealTimeScheduler"
> sim-time-limit = 3600s
> cmdenv-express-mode = false
> 
> **.crcMode = "computed"
> **.fcsMode = "computed"
> 
> [Config ExternalCommunication]
> network = ExternalCommunication
> description = "UDP tunneling through Omnet++"
> 
> # Using inline XML configuration
> *.configurator.config = xml("<config> \
>                                 <interface hosts='host0' names='eth0' address='10.0.0.1'/> \
>                                 <interface hosts='host1' names='eth0' address='10.0.1.1'/> \
> 				<interface hosts='router' names='eth0' address='10.0.0.100'/> \
>                                 <interface hosts='router' names='eth1' address='10.0.1.100'/> \
>                              </config>")
> 
> *.host0.eth[0].typename = "ExtUpperEthernetInterface"
> *.host0.eth[0].namespace = "host0"
> *.host0.eth[0].device = "tap0"
> *.host0.eth[0].copyConfiguration = "copyFromExt"
> 
> 
> *.host1.eth[0].typename = "ExtUpperEthernetInterface"
> *.host1.eth[0].namespace = "host1"
> *.host1.eth[0].device = "tap1"
> *.host1.eth[0].copyConfiguration = "copyFromExt"
> ```

When I run in the third step omnetini encountered such a problem always change a network namespace -- in the module (inet: : ExtEthernetTapDevice) ExternalCommunication. Host0. Eth [0]. Tap (id = 24), during the network initialization. I don't know why this is happening, could you please look at it, thank you again

**Comment by zhangteng0526** [comment]
> SOLVED
> 
> ```
> [General]
> scheduler-class = "inet::RealTimeScheduler"
> sim-time-limit = 3600s
> cmdenv-express-mode = false
> 
> **.crcMode = "computed"
> **.fcsMode = "computed"
> 
> [Config ExternalCommunication]
> network = ExternalCommunication
> description = "UDP tunneling through Omnet++"
> 
> # Using inline XML configuration
> *.configurator.config = xml("<config> \
>                                 <interface hosts='host0' names='eth0' address='10.0.0.1'/> \
>                                 <interface hosts='host1' names='eth0' address='10.0.1.1'/> \
> 				<interface hosts='router' names='eth0' address='10.0.0.100'/> \
>                                 <interface hosts='router' names='eth1' address='10.0.1.100'/> \
>                              </config>")
> 
> *.host0.eth[0].typename = "ExtUpperEthernetInterface"
> *.host0.eth[0].namespace = "host0"
> *.host0.eth[0].device = "tap0"
> *.host0.eth[0].copyConfiguration = "copyFromExt"
> 
> 
> *.host1.eth[0].typename = "ExtUpperEthernetInterface"
> *.host1.eth[0].namespace = "host1"
> *.host1.eth[0].device = "tap1"
> *.host1.eth[0].copyConfiguration = "copyFromExt"
> ```

When I ran the omnetini file in step 3, I ran into this problem
Cannot change network namespace -- in module (inet::ExtEthernetTapDevice) ExternalCommunication.host0.eth[0].tap  (id=24), during network initialization
I don't know why this happened, I hope you can spare some time to help look it over, thank you again
