### ISSUE TITLE
Reproducibility of coexistence showcase (802.11 and 802.15.4 over 2.4GHz) 

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet-showcases#38]
This showcase doc (https://github.com/inet-framework/inet-showcases/blob/topic/coexistence/wireless/coexistence/doc/index.rst) refers to INET 4.0, but this release has not dimensional models for IEEE802.15.4. Hence, one cannot reproduce the simulation scenario. 
(Should it be INET 4.1?)

**Comment by adamgeorge309** [comment]
You are right, version changed to 4.1 in topic branch. Thanks!

**Comment by ababila** [comment]
Nevertheless, I still have difficulty reproducing the degradation of performance of the documentation. 
(Would there be any information missing in the omnet.ini/CoexistenceShowcase.ned file?)

**Comment by adamgeorge309** [comment]
This showcase is a work-in-progress right now, but the version on the showcases wip branch should work.

**Comment by ababila** [comment]
Oh, right, I see, thank you.

**Comment by ababila** [comment]
I still can't get the expected results even (with the showcase of the wip branch). 
For instance, the received packet for wpan are 49 under coexistence or not.
![wpan](https://user-images.githubusercontent.com/36278932/55745797-5ad3a900-5a38-11e9-8995-0374282b2b78.png)

![wifi](https://user-images.githubusercontent.com/36278932/55745793-56a78b80-5a38-11e9-9751-d69f2cf6d49b.png)

(I even run the model in another platform (windows) :).  )

**Comment by ababila** [comment]
(1) **.dimensions ="time frequency" should be set (for example) in the omnetpp.ini file, by default dimensions are time only (contrary to what is said in the crosstalk's doc). 

(2) Moreover, when the bandwidth parameter of the wifi radio.transmitter is also not set anywhere, the Ieee80211DimensionalTransmitter creates signals without real power values, which leads to unsuccessful receptions (because of nan SNIR values), hence total packet loss at the wifi receiver. I think this should be another aspect of this bug: https://github.com/inet-framework/inet/issues/427

**Comment by adamgeorge309** [comment]
You're right on both points. The **.dimensions ="time frequency" as default didn't make it to master yet. You may be able to fix (2) with this commit on master:

https://github.com/inet-framework/inet/commit/1a8a69a09f3253cba0cc20c1ae9417086a651cd9

Also, in Ieee80211Radio.ned, set the bandwidth to 20MHz.
